[profile.default]
solc = "0.8.19"
src = "contracts"
test = "forge-test"
libs = ["lib", "node_modules"]
optimizer = true
optimizer_runs = 50
evm_version = "london"
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/",
  "forge-std/=lib/forge-std/src/"
]
fs_permissions = [{ access = "read", path = "./" }]
